
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LIBRE
 */
public class calculadoraxd extends javax.swing.JFrame {

    ScriptEngineManager sem=new ScriptEngineManager();
    ScriptEngine se=sem.getEngineByName("JavaScript");
    /**
     * Creates new form calculadoraxd
     */
    public calculadoraxd() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        operacion = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        c = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        raiz = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        parentesis1 = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        multiplicar = new javax.swing.JButton();
        reciproco = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        restar = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        sumar = new javax.swing.JButton();
        parentesis2 = new javax.swing.JButton();
        encender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("calculadora 7w7 ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("calculadorazpatex 7w7"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        operacion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        operacion.setForeground(new java.awt.Color(153, 102, 255));
        operacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(operacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, 30));

        resultado.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        resultado.setForeground(new java.awt.Color(153, 0, 255));
        resultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 100));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        c.setForeground(new java.awt.Color(255, 255, 255));
        c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        c.setText("C");
        c.setBorderPainted(false);
        c.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c.setFocusPainted(false);
        c.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        c.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        c.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel2.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        borrar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        borrar.setForeground(new java.awt.Color(255, 255, 255));
        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        borrar.setText("<-");
        borrar.setBorderPainted(false);
        borrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrar.setFocusPainted(false);
        borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        borrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jPanel2.add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        raiz.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        raiz.setForeground(new java.awt.Color(255, 255, 255));
        raiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        raiz.setText("√");
        raiz.setBorderPainted(false);
        raiz.setContentAreaFilled(false);
        raiz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        raiz.setFocusPainted(false);
        raiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        raiz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        raiz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizActionPerformed(evt);
            }
        });
        jPanel2.add(raiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 50, 50));

        siete.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        siete.setForeground(new java.awt.Color(255, 255, 255));
        siete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        siete.setText("7");
        siete.setBorderPainted(false);
        siete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siete.setFocusPainted(false);
        siete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        siete.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        siete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });
        jPanel2.add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 50, 50));

        ocho.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        ocho.setForeground(new java.awt.Color(255, 255, 255));
        ocho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        ocho.setText("8");
        ocho.setBorderPainted(false);
        ocho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ocho.setFocusPainted(false);
        ocho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ocho.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        ocho.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });
        jPanel2.add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 50, 50));

        nueve.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        nueve.setForeground(new java.awt.Color(255, 255, 255));
        nueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        nueve.setText("9");
        nueve.setBorderPainted(false);
        nueve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nueve.setFocusPainted(false);
        nueve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nueve.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        nueve.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });
        jPanel2.add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 50, 50));

        dividir.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        dividir.setForeground(new java.awt.Color(255, 255, 255));
        dividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        dividir.setText("/");
        dividir.setBorderPainted(false);
        dividir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dividir.setFocusPainted(false);
        dividir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dividir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        dividir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });
        jPanel2.add(dividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 50, 50));

        parentesis1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        parentesis1.setForeground(new java.awt.Color(255, 255, 255));
        parentesis1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        parentesis1.setText("(");
        parentesis1.setBorderPainted(false);
        parentesis1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        parentesis1.setFocusPainted(false);
        parentesis1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        parentesis1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        parentesis1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        parentesis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesis1ActionPerformed(evt);
            }
        });
        jPanel2.add(parentesis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        cuatro.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        cuatro.setForeground(new java.awt.Color(255, 255, 255));
        cuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        cuatro.setText("4");
        cuatro.setBorderPainted(false);
        cuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuatro.setFocusPainted(false);
        cuatro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuatro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        cuatro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });
        jPanel2.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 50, 50));

        cinco.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        cinco.setForeground(new java.awt.Color(255, 255, 255));
        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        cinco.setText("5");
        cinco.setBorderPainted(false);
        cinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cinco.setFocusPainted(false);
        cinco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cinco.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        cinco.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        jPanel2.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 50, 50));

        seis.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        seis.setForeground(new java.awt.Color(255, 255, 255));
        seis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        seis.setText("6");
        seis.setBorderPainted(false);
        seis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seis.setFocusPainted(false);
        seis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seis.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        seis.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        jPanel2.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 50, 50));

        multiplicar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        multiplicar.setForeground(new java.awt.Color(255, 255, 255));
        multiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        multiplicar.setText("*");
        multiplicar.setBorderPainted(false);
        multiplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multiplicar.setFocusPainted(false);
        multiplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        multiplicar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        multiplicar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarActionPerformed(evt);
            }
        });
        jPanel2.add(multiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 50, 50));

        reciproco.setFont(new java.awt.Font("GungsuhChe", 0, 11)); // NOI18N
        reciproco.setForeground(new java.awt.Color(255, 255, 255));
        reciproco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        reciproco.setText("1/x");
        reciproco.setBorderPainted(false);
        reciproco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reciproco.setFocusPainted(false);
        reciproco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reciproco.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        reciproco.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        reciproco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reciprocoActionPerformed(evt);
            }
        });
        jPanel2.add(reciproco, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 50, 50));

        uno.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        uno.setForeground(new java.awt.Color(255, 255, 255));
        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        uno.setText("1");
        uno.setBorderPainted(false);
        uno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uno.setFocusPainted(false);
        uno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uno.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        uno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        jPanel2.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 50, 50));

        dos.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        dos.setForeground(new java.awt.Color(255, 255, 255));
        dos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        dos.setText("2");
        dos.setBorderPainted(false);
        dos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dos.setFocusPainted(false);
        dos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        dos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });
        jPanel2.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 50, 50));

        tres.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        tres.setForeground(new java.awt.Color(255, 255, 255));
        tres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        tres.setText("3");
        tres.setBorderPainted(false);
        tres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tres.setFocusPainted(false);
        tres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tres.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        tres.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        jPanel2.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 50, 50));

        restar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        restar.setForeground(new java.awt.Color(255, 255, 255));
        restar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        restar.setText("-");
        restar.setBorderPainted(false);
        restar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restar.setFocusPainted(false);
        restar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        restar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        restar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restarActionPerformed(evt);
            }
        });
        jPanel2.add(restar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 50, 50));

        igual.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        igual.setForeground(new java.awt.Color(255, 255, 255));
        igual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/=.png"))); // NOI18N
        igual.setText("=");
        igual.setBorderPainted(false);
        igual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        igual.setFocusPainted(false);
        igual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        igual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/=.png"))); // NOI18N
        igual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/=2.png"))); // NOI18N
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        jPanel2.add(igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 50, 100));

        cero.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        cero.setForeground(new java.awt.Color(255, 255, 255));
        cero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cero.png"))); // NOI18N
        cero.setText("0");
        cero.setBorderPainted(false);
        cero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cero.setFocusPainted(false);
        cero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cero.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cero.png"))); // NOI18N
        cero.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/00.png"))); // NOI18N
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });
        jPanel2.add(cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 100, 50));

        punto.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        punto.setForeground(new java.awt.Color(255, 255, 255));
        punto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        punto.setText(".");
        punto.setBorderPainted(false);
        punto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        punto.setFocusPainted(false);
        punto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        punto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        punto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });
        jPanel2.add(punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 50, 50));

        sumar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        sumar.setForeground(new java.awt.Color(255, 255, 255));
        sumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        sumar.setText("+");
        sumar.setBorderPainted(false);
        sumar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sumar.setFocusPainted(false);
        sumar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sumar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        sumar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });
        jPanel2.add(sumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 50, 50));

        parentesis2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        parentesis2.setForeground(new java.awt.Color(255, 255, 255));
        parentesis2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        parentesis2.setText(")");
        parentesis2.setBorderPainted(false);
        parentesis2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        parentesis2.setFocusPainted(false);
        parentesis2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        parentesis2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        parentesis2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito2.png"))); // NOI18N
        parentesis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesis2ActionPerformed(evt);
            }
        });
        jPanel2.add(parentesis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 50, 50));

        encender.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        encender.setForeground(new java.awt.Color(255, 255, 255));
        encender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/off.png"))); // NOI18N
        encender.setBorderPainted(false);
        encender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encender.setFocusPainted(false);
        encender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        encender.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        encender.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadradito.png"))); // NOI18N
        encender.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/on.png"))); // NOI18N
        encender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encenderActionPerformed(evt);
            }
        });
        jPanel2.add(encender, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        operacion.setText("");
        resultado.setText("");
    }//GEN-LAST:event_cActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        String deletear=operacion.getText().substring(0,operacion.getText().length()-1);
        operacion.setText(deletear);
// TODO add your handling code here:
    }//GEN-LAST:event_borrarActionPerformed

    private void parentesis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesis2ActionPerformed
        agregarTexto(")");// TODO add your handling code here:
    }//GEN-LAST:event_parentesis2ActionPerformed

    private void encenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encenderActionPerformed

        if(!aux){
            encender.setIcon(new ImageIcon(getClass().getResource("/img/on.png")));
            siete.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            seis.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            cinco.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            cuatro.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            tres.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            dos.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            uno.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            nueve.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            ocho.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            borrar.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            c.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            cero.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cero.png")));
            dividir.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            igual.setRolloverIcon(new ImageIcon(getClass().getResource("/img/=.png")));
            multiplicar.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            parentesis1.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            parentesis2.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            punto.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            raiz.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            reciproco.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            restar.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            sumar.setRolloverIcon(new ImageIcon(getClass().getResource("/img/cuadradito.png")));
            siete.setForeground(Color.decode("#0a0a0a"));
            ocho.setForeground(Color.decode("#0a0a0a"));
            nueve.setForeground(Color.decode("#0a0a0a"));
            cero.setForeground(Color.decode("#0a0a0a"));
            uno.setForeground(Color.decode("#0a0a0a"));
            dos.setForeground(Color.decode("#0a0a0a"));
            tres.setForeground(Color.decode("#0a0a0a"));
            cuatro.setForeground(Color.decode("#0a0a0a"));
            cinco.setForeground(Color.decode("#0a0a0a"));
            seis.setForeground(Color.decode("#0a0a0a"));
            c.setForeground(Color.decode("#0a0a0a"));
            borrar.setForeground(Color.decode("#0a0a0a"));
            raiz.setForeground(Color.decode("#0a0a0a"));
            dividir.setForeground(Color.decode("#0a0a0a"));
            igual.setForeground(Color.decode("#0a0a0a"));
            multiplicar.setForeground(Color.decode("#0a0a0a"));
            operacion.setForeground(Color.decode("#0a0a0a"));
            resultado.setForeground(Color.decode("#0a0a0a"));
            parentesis1.setForeground(Color.decode("#0a0a0a"));
            parentesis2.setForeground(Color.decode("#0a0a0a"));
            punto.setForeground(Color.decode("#0a0a0a"));
            reciproco.setForeground(Color.decode("#0a0a0a"));
            restar.setForeground(Color.decode("#0a0a0a"));
            sumar.setForeground(Color.decode("#0a0a0a"));
            
            aux=true;
        }
        else{
            calculadoraxd frame = new calculadoraxd();
            this.dispose();
            frame.setVisible(true);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_encenderActionPerformed

    private void raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizActionPerformed
        operacion.setText("Math.sqrt("+operacion.getText()+")");// TODO add your handling code here:
    }//GEN-LAST:event_raizActionPerformed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        agregarTexto("7");
// TODO add your handling code here:
    }//GEN-LAST:event_sieteActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        agregarTexto("8");// TODO add your handling code here:
    }//GEN-LAST:event_ochoActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        agregarTexto("9");// TODO add your handling code here:
    }//GEN-LAST:event_nueveActionPerformed

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirActionPerformed
        agregarTexto("/");// TODO add your handling code here:
    }//GEN-LAST:event_dividirActionPerformed

    private void parentesis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesis1ActionPerformed
        agregarTexto("(");// TODO add your handling code here:
    }//GEN-LAST:event_parentesis1ActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        agregarTexto("4");// TODO add your handling code here:
    }//GEN-LAST:event_cuatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        agregarTexto("5");// TODO add your handling code here:
    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        agregarTexto("6");// TODO add your handling code here:
    }//GEN-LAST:event_seisActionPerformed

    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicarActionPerformed
        agregarTexto("*");// TODO add your handling code here:
    }//GEN-LAST:event_multiplicarActionPerformed

    private void reciprocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reciprocoActionPerformed
        operacion.setText("1/("+operacion.getText()+")");
// TODO add your handling code here:
    }//GEN-LAST:event_reciprocoActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        agregarTexto("1");// TODO add your handling code here:
    }//GEN-LAST:event_unoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        agregarTexto("2");// TODO add your handling code here:
    }//GEN-LAST:event_dosActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        agregarTexto("3");// TODO add your handling code here:
    }//GEN-LAST:event_tresActionPerformed

    private void restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restarActionPerformed
        agregarTexto("-");// TODO add your handling code here:
    }//GEN-LAST:event_restarActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        try {
            String r= se.eval(operacion.getText()).toString();
            resultado.setText(r);
// TODO add your handling code here:
        } catch (ScriptException ex) {
            Logger.getLogger(calculadoraxd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_igualActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        agregarTexto("0");// TODO add your handling code here:
    }//GEN-LAST:event_ceroActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        agregarTexto(".");// TODO add your handling code here:
    }//GEN-LAST:event_puntoActionPerformed

    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
        agregarTexto("+");// TODO add your handling code here:
    }//GEN-LAST:event_sumarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadoraxd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadoraxd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadoraxd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadoraxd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadoraxd().setVisible(true);
            }
        });
    }

    boolean aux=false;
    public void agregarTexto (String digito){
        operacion.setText(operacion.getText()+ digito);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton c;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton dividir;
    private javax.swing.JButton dos;
    private javax.swing.JButton encender;
    private javax.swing.JButton igual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton multiplicar;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JLabel operacion;
    private javax.swing.JButton parentesis1;
    private javax.swing.JButton parentesis2;
    private javax.swing.JButton punto;
    private javax.swing.JButton raiz;
    private javax.swing.JButton reciproco;
    private javax.swing.JButton restar;
    private javax.swing.JLabel resultado;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton sumar;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables
}
